# Generated by Django 4.2.30 on 2026-04-09 16:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('contact_phone', models.CharField(default='502-319-0546', max_length=30)),
                ('contact_email', models.EmailField(default='zrichardson@rich360.io', max_length=254)),
                ('thank_you_text', models.CharField(default='Thank you for your response.', max_length=300)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ForAgenciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_headline', models.CharField(default='Scale Your Analytics.', max_length=200)),
                ('hero_subheadline', models.CharField(default='No Overhead. No Contracts.', max_length=200)),
                ('hero_body', models.TextField(default='We offer white-labeled data solutions for agencies covering Google Analytics, Google Tag Manager, and Adobe Analytics management with flexible account scaling.')),
                ('feature_headline', models.CharField(default='Fully Managed Dashboards, Ready for Your Clients', max_length=200)),
                ('feature_body', models.TextField(default='Custom dashboard creation across platforms (Power BI, Looker Studio, Tableau) with data integration, automation, and branding.')),
                ('secondary_headline', models.CharField(default='Scalable. Seamless. Yours.', max_length=200)),
                ('secondary_body', models.TextField(default="Our managed analytics services adapt to your agency's growth—add or remove accounts with no long-term commitment.")),
            ],
            options={
                'verbose_name': 'For Agencies Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ForBusinessesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_headline', models.CharField(default='Streamline Your Data.', max_length=200)),
                ('hero_subheadline', models.CharField(default='Automate Your Reports.', max_length=200)),
                ('hero_body', models.TextField(default='We help businesses eliminate spreadsheet dependency by automating reporting processes, constructing scalable data infrastructure, and developing interactive dashboards. Our data engineering expertise ensures information is properly organized and continuously refreshed without requiring manual intervention.')),
                ('feature_headline', models.CharField(default='Building Your Data Foundation', max_length=200)),
                ('feature_body', models.TextField(default='For organizations still using spreadsheets or disorganized data systems, we provide streamlined, automated mechanisms for data collection, storage, and visualization—enabling you to obtain necessary insights without technical complexity or expanding skill requirements.')),
            ],
            options={
                'verbose_name': 'For Businesses Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_headline',
            field=models.CharField(default='Start Your Data Transformation', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_subheading',
            field=models.CharField(default="See how better data can drive better results—let's talk.", max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_body',
            field=models.TextField(default='Specializing in data engineering and analytics, we help businesses organize and explore their data for better decision-making.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(default='SEE THE TRENDS.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheadline',
            field=models.CharField(default='SHAPE THE FUTURE.', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {})}),
        ),
        migrations.CreateModel(
            name='ContactFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
